### PR TITLE
ci: github action ci and semantic release

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>

Fix: #87 add github action ci and semantic release

plz do not use gorm version over 1.20.x, new version is still unstable.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@closetool plz fix:

image

**Comment by closetool** [comment]
@hsluoyz fixed
coveralls is not supported, because I can't ...
image

**Comment by hsluoyz** [comment]
@closetool , ok, can you test if the auto-release works? Maybe use a PR with a "fix: xxx" title (maybe improve the README a little or something else)

**Comment by closetool** [comment]
@hsluoyz No need, cause the new version has been published
image

**Comment by hsluoyz** [comment]
@closetool great, thanks!

**Pull request merged**
