### PR TITLE
feat: update gorm and gorm-drivers

### PR DESCRIPTION
**Pull request by dsuket**
update  gorm and gorm-drivers to latest.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@dsuket fix:

image

**Comment by dsuket** [comment]
@hsluoyz Thank you for your information. I agreed license.

**Comment by dsuket** [comment]
But, build faled.
```
Error: ../../../go/pkg/mod/gorm.io/gorm@v1.24.0/logger/logger.go:72:24: undefined: io.Discard
```
It seemd Go version is lower. `io.Discard` used by `gorm/logger` is avaliable from Go 1.16.
Could i update go-version of ci to 1.16?

**Comment by hsluoyz** [comment]
@dsuket OK

**Comment by dsuket** [comment]
I fixed go version for ci.
Please, check it again.

**Comment by hsluoyz** [comment]
@dsuket sign CLA

**Comment by dsuket** [comment]
Sorry, I signed CLA again.

**Pull request merged**
