### PR TITLE
feat: support empty policy field

### PR DESCRIPTION
**Pull request by snyh**
see also: https://github.com/casbin/casbin/issues/316

### CODE REVIEW

**Comment by snyh** [comment]
@hsluoyz  
我用这个的目的是，类似 `/api/login`这种在还无法获得`uid`时，使用空字符串代表"任何subject" (虽然也可以使用"*"代表，然后修改model.matcher。但matcher只能写一个，用&&,||拼凑过多的内容不利于理解)

**Comment by hsluoyz** [comment]
Hi @snyh can you modify your words into English? We are an international open-source project

**Comment by snyh** [comment]
> Hi @snyh can you modify your words into English? We are an international open-source project

done :)

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
