### PR TITLE
update gorm to 1.20.7

### PR DESCRIPTION
**Pull request by thnt**

### CODE REVIEW

**Comment by nodece** [comment]
@thnt please fix the https://github.com/casbin/gorm-adapter/pull/59/checks?check_run_id=1429948046.

**Comment by hsluoyz** [comment]
@thnt please fix the CI: https://travis-ci.org/github/casbin/gorm-adapter/builds/744848926

image

**Comment by 00LT00** [comment]
plz fix DCO @thnt

**Review by 00LT00 — APPROVED** [review]
LGTM

**Review by nodece — APPROVED** [review]

**Pull request merged**
