### PR TITLE
remove WithConditions: true

### PR DESCRIPTION
**Pull request by seefs001**
Fix: https://github.com/casbin/gorm-adapter/issues/58

### CODE REVIEW

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
@miaolz123 why do we use WithConditions at the first time? https://github.com/casbin/gorm-adapter/commit/a0a102ddb783ac8016ebfaa5f6d1790a8c7330ef

https://github.com/casbin/gorm-adapter/blob/dcbefd9ab8a71b76ce1c4e078878c861a36e63b2/adapter.go#L167-L174

https://github.com/casbin/gorm-adapter/blob/dcbefd9ab8a71b76ce1c4e078878c861a36e63b2/adapter.go#L248-L249

**Comment by hsluoyz** [comment]
@seefs001 why do you want to remove WithConditions ?

**Comment by seefs001** [comment]
@hsluoyz https://github.com/go-gorm/gorm/commit/26504f5caeb8c31dff62e8ddab68cee6b85a6580

**Comment by hsluoyz** [comment]
@seefs001 can you fix the PR: https://github.com/casbin/gorm-adapter/pull/59 first?

**Comment by nodece** [comment]
fixed by: #58

**Comment by nodece** [comment]
please  bump your `gorm-adapter` to v3.0.4.

**Pull request closed without merging**
