### PR TITLE
add unique index

### PR DESCRIPTION
**Pull request by 00LT00**
Fix: https://github.com/casbin/gorm-adapter/issues/35

### CODE REVIEW

**Comment by hsluoyz** [comment]
@00LT00 please fix the CI error.

**Comment by hsluoyz** [comment]
@aofengli please review.

**Comment by 00LT00** [comment]
Now I have a problem. In my environment, if you add the ID column directly, mysql will report an error 1075. But if you re-create the table, that's ok.  I had report this bug to gorm, but no answer. 
So if user update the version of gorm-adapter, he maybe get the same error ( I can't make sure this error for other machine).
In my opinions, add ID can avoid some error that the order of policy are different on different environment. 
@hsluoyz

**Comment by hsluoyz** [comment]
> I had report this bug to gorm, but no answer.

Can you provide the link to this gorm bug?

**Comment by hsluoyz** [comment]
@00LT00

**Comment by 00LT00** [comment]
https://github.com/go-gorm/gorm/issues/3537

**Review by nodece — APPROVED** [review]
@hsluoyz , @00LT00 LGTM, but I'm not sure if it's compatible with the previous version.

**Comment by hsluoyz** [comment]
Let's release v4.0.0 to show this breaking change.

**Comment by nodece** [comment]
@00LT00 Could you update go.mod for bump to v4?

**Pull request merged**
