### PR TITLE
Implement AddPolicies and RemovePolicies 

### PR DESCRIPTION
**Pull request by dallen42**

### CODE REVIEW

**Comment by hsluoyz** [comment]
There are lots of unrelated commits.

**Comment by jedi4z** [comment]
Hi! I got this error `panic: interface conversion: *gormadapter.Adapter is not persist.BatchAdapter: missing method AddPolicies` trying to use `AddGroupingPolicies`, this PR is related?

**Comment by hsluoyz** [comment]
@nodece if this PR cannot pass, we should fix the error first. Can you follow this issue?

**Comment by dallen42** [comment]
@nodece sorry, have been busy. I created a new PR without any extra commits. Will close this one

**Pull request closed without merging**
